In [ ]:
NORMALIZATION PROBLEM

In [2]:
import numpy as np

X = np.random.rand (5,5)

mean = X.mean()
std = X.std()

X_normalized = (X-mean) / std

np.save ("X_normalized.npy", X_normalized)

In [3]:
print("Original Array (X):\n", X)
print("\nNormalized Array (X_normalized):\n", X_normalized)

Original Array (X):
 [[0.0240948  0.89633027 0.70642153 0.23632005 0.21597267]
 [0.06738925 0.85043024 0.98274354 0.57407844 0.04764572]
 [0.36073476 0.62891875 0.86682271 0.67086708 0.18198347]
 [0.16145933 0.25793274 0.40257288 0.86066663 0.62840394]
 [0.795553   0.37424383 0.79194966 0.43020583 0.52926746]]

Normalized Array (X_normalized):
 [[-1.62728865  1.34445123  0.69742483 -0.90422902 -0.97355332]
 [-1.47978279  1.18806806  1.63886457  0.24652683 -1.54704975]
 [-0.48034333  0.43336987  1.24391783  0.57628946 -1.08935587]
 [-1.15928238 -0.83059376 -0.33779922  1.22294384  0.43161591]
 [ 1.00109919 -0.43431739  0.98882247 -0.2436527   0.0938541 ]]


In [5]:
print("\nMean: ", mean)
print("\nStandard Deviation: ", std)


Mean:  0.5017203421335107

Standard Deviation:  0.2935100332391841


In [ ]:
DIVISIBLE BY 3 PROBLEM

In [6]:
import numpy as np

numbers = np.arange (1, 101)
squares = numbers**2

A = squares.reshape (10, 10)

div_by_3 = A[A % 3 == 0]

np.save ("div_by_3.npy", div_by_3)

In [7]:
print("Matrix A (10x10 of squares):\n", A)
print("\nElements divisible by 3:\n", div_by_3)

Matrix A (10x10 of squares):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
